language: python

python:
  - '2.6'
  - '2.7'
  - 'pypy'
  - '3.3'
  - '3.4'

install: 'pip install .'

before_script: 'pip install python-coveralls'

script: 'python setup.py test'

after_success: 'coveralls -i'
